# Generated by Django 3.0.6 on 2020-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/profile/'),
        ),
    ]
