# Generated by Django 3.0.6 on 2020-09-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='images/profile/'),
        ),
    ]
