# Generated by Django 3.0.6 on 2020-09-11 22:51

from django.db import migrations, models
import logregapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0004_auto_20200910_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to=logregapp.models.upload_to, verbose_name='Photo'),
        ),
    ]
