# Generated by Django 3.0.6 on 2020-09-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbarnapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
