# Generated by Django 3.0.6 on 2020-09-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0002_auto_20200913_1624'),
        ('bookbarnapp', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requested_books', to='logregapp.User'),
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_book', to='bookbarnapp.Book')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requestor', to='logregapp.User')),
            ],
        ),
    ]
