# Generated by Django 3.0.6 on 2020-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbarnapp', '0003_auto_20200907_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
