# Generated by Django 3.0.6 on 2020-09-15 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0002_auto_20200913_1624'),
        ('bookbarnapp', '0003_auto_20200913_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_comment', to='logregapp.User')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_request', to='bookbarnapp.Requests')),
            ],
        ),
    ]
